name: map_hunter
description: Real Life RPG - MapHunter con elementos de juego de rol

publish_to: "none"
version: 1.0.1+2

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  supabase_flutter: ^2.12.0
  audioplayers: ^6.1.0
  confetti: ^0.8.0
  video_player: ^2.8.1
  video_player_win: ^3.1.5

  # UI & Icons
  cupertino_icons: ^1.0.2
  auto_size_text: ^3.0.0

  # State Management
  provider: ^6.1.5+1

  # Utilities
  intl: ^0.20.2
  image_picker: ^1.2.1
  file_picker: ^10.3.10 # For Windows compatibility
  flutter_dotenv: ^6.0.0
  google_maps_flutter: ^2.14.0
  geolocator: ^14.0.2
  flutter_map: ^8.2.2
  latlong2: ^0.9.0
  http: ^1.1.0
  qr_flutter: ^4.1.0
  mobile_scanner: ^7.1.4
  uuid: ^4.5.2
  shared_preferences: ^2.5.4

  # PDF & Printing
  pdf: ^3.10.4
  printing: ^5.11.0
  url_launcher: ^6.3.2
  package_info_plus: ^8.0.0
  webview_flutter: ^4.13.1
  webview_windows: ^0.4.0
  sensors_plus: ^7.0.0
  onesignal_flutter: ^5.3.3
  flutter_secure_storage: ^10.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  web:
    generate: true
    image_path: "assets/images/app_icon.png"
    background_color: "#0D0D0F"
    theme_color: "#FECB00"
  image_path: "assets/images/app_icon.png"
  # Para Android 8.0+ (Iconos adaptativos)
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/app_icon.png"

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/audio/
    - assets/images/
    - assets/images/personajesgrupal.png
    - assets/images/avatars/
    - assets/escenarios.avatar/
