name: treasure_hunt_rpg
description: Real Life RPG - BÃºsqueda del Tesoro con elementos de juego de rol

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  supabase_flutter: ^2.5.0
  
  # UI & Icons
  cupertino_icons: ^1.0.2
  
  # State Management
  provider: ^6.1.5+1
  
  # Utilities
  intl: ^0.18.1
  image_picker: ^1.2.1
  flutter_dotenv: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  assets:
    - .env
    - assets/images/
    - assets/icons/
    - assets/lottie/

